version: '3.3'

services:

  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE:-dvoykin/app}
    links:
      - mongo
    environment:
     - MONGO_SERVICE_URI=
     - MONGO_SERVICE_HOST=mongo
     - MONGO_SERVICE_PORT=27017
     - MONGO_SERVICE_DB=test
    ports:
     - "27017:27017"
    command: node /app/bin/run.js
    
  mongo:
    image: mongo:latest